name: RP FR CLEAN
tasks:
  - action: download_github
    src: https://github.com/Vincx12/gta
    ref: main
    dest: ./temp

  - action: move_path
    src: ./temp/resources
    dest: ./resources

  - action: move_path
    src: ./temp/recipe_files/server.cfg
    dest: ./server.cfg
